# Generated by Django 5.2.8 on 2025-11-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_equipment', models.IntegerField()),
                ('avg_flowrate', models.FloatField()),
                ('avg_pressure', models.FloatField()),
                ('avg_temperature', models.FloatField()),
            ],
        ),
    ]
