# Generated by Django 5.2.8 on 2025-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='preview_rows',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_flowrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
