# Generated by Django 5.2.8 on 2025-11-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipmentdataset_preview_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdataset',
            name='total_equipment',
            field=models.IntegerField(default=0),
        ),
    ]
