# Generated by Django 5.2.8 on 2025-11-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_equipmentdataset_total_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdataset',
            name='avg_flowrate',
        ),
        migrations.RemoveField(
            model_name='equipmentdataset',
            name='avg_pressure',
        ),
        migrations.RemoveField(
            model_name='equipmentdataset',
            name='avg_temperature',
        ),
        migrations.RemoveField(
            model_name='equipmentdataset',
            name='preview_rows',
        ),
        migrations.RemoveField(
            model_name='equipmentdataset',
            name='total_equipment',
        ),
    ]
