# Generated by Django 5.2.8 on 2025-11-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_equipmentdataset_avg_flowrate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentdataset',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='summary',
            field=models.JSONField(default={'averages': {'Flowrate': 0, 'Pressure': 0, 'Temperature': 0}, 'invalid_entries': 0, 'missing_values': 0, 'monthly': {'flowrate': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'pressure': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'temperature': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, 'total_count': 0, 'type_distribution': {}, 'valid_rows': 0}),
            preserve_default=False,
        ),
    ]
